export type ModuleMetric = {
  label: string;
  value: string;
  detail: string;
  tone?: "positive" | "warning" | "neutral";
};

export type ModuleConfig = {
  title: string;
  eyebrow: string;
  description: string;
  action: string;
  metrics: ModuleMetric[];
  workflow: string[];
  columns: string[];
  rows: Record<string, string>[];
  insight: string;
};

export const moduleConfigs: Record<string, ModuleConfig> = {
  inbox: {
    title: "Unified inbox",
    eyebrow: "Attention queue",
    description: "Client requests, approvals, lead replies, and internal mentions—triaged in one place.",
    action: "Compose",
    metrics: [
      { label: "Needs reply", value: "8", detail: "3 client-facing", tone: "warning" },
      { label: "Awaiting approval", value: "5", detail: "$36.2k affected" },
      { label: "SLA health", value: "94%", detail: "+4% this month", tone: "positive" },
      { label: "Median response", value: "1h 18m", detail: "Target under 4h" },
    ],
    workflow: ["Untriaged", "Assigned", "Waiting", "Resolved"],
    columns: ["Message", "From", "Context", "Owner", "Received"],
    rows: [
      { Message: "Can we add analytics to the handoff?", From: "Northstar Labs", Context: "NST-024", Owner: "Avery", Received: "18 min ago" },
      { Message: "Homepage direction approved", From: "Fieldnote Studio", Context: "FLD-008", Owner: "Sam", Received: "42 min ago" },
      { Message: "Question about invoice schedule", From: "Halcyon Health", Context: "INV-2026-046", Owner: "Mina", Received: "1h ago" },
      { Message: "New referral: Lumen Works", From: "Maya Chen", Context: "Lead", Owner: "Unassigned", Received: "2h ago" },
    ],
    insight: "Two messages can be resolved from existing project context; M&W Intelligence has drafted replies for review.",
  },
  leads: {
    title: "Lead pipeline",
    eyebrow: "Revenue engine",
    description: "Capture, qualify, and progress every opportunity with clear ownership and next steps.",
    action: "Add lead",
    metrics: [
      { label: "Open pipeline", value: "$114k", detail: "5 opportunities", tone: "positive" },
      { label: "Weighted value", value: "$62.7k", detail: "+12.4% this month", tone: "positive" },
      { label: "Win rate", value: "38%", detail: "Target 42%" },
      { label: "Avg. sales cycle", value: "23 days", detail: "4 days faster", tone: "positive" },
    ],
    workflow: ["Enquiry", "Fit review", "Discovery booked", "Discovery", "Proposal", "Decision"],
    columns: ["Opportunity", "Stage", "Value", "Score", "Owner", "Next step"],
    rows: [
      { Opportunity: "Vela Systems", Stage: "Proposal", Value: "$28,000", Score: "92", Owner: "Mina Park", "Next step": "Revise scope · Today" },
      { Opportunity: "Nova Commerce", Stage: "Discovery", Value: "$18,000", Score: "84", Owner: "Avery Kim", "Next step": "Discovery call · Fri" },
      { Opportunity: "Common Ground", Stage: "Qualified", Value: "$12,500", Score: "76", Owner: "Mina Park", "Next step": "Send credentials · Today" },
      { Opportunity: "Juniper AI", Stage: "New", Value: "$34,000", Score: "71", Owner: "Sam Rivera", "Next step": "Qualify brief · Mon" },
      { Opportunity: "Forma Living", Stage: "Negotiation", Value: "$22,000", Score: "95", Owner: "Avery Kim", "Next step": "Commercial call · Thu" },
    ],
    insight: "Prioritize Vela Systems today. Similar proposals close 3× more often when revised within 24 hours.",
  },
  proposals: {
    title: "Proposals",
    eyebrow: "Commercial studio",
    description: "Build scoped, margin-aware proposals and move accepted work directly into delivery.",
    action: "New proposal",
    metrics: [
      { label: "Draft value", value: "$46k", detail: "3 proposals" },
      { label: "Awaiting decision", value: "$50k", detail: "2 proposals", tone: "warning" },
      { label: "Acceptance rate", value: "61%", detail: "+7% quarter over quarter", tone: "positive" },
      { label: "Avg. margin", value: "58%", detail: "3% above target", tone: "positive" },
    ],
    workflow: ["Draft", "Internal review", "Sent", "Viewed", "Accepted", "Converted"],
    columns: ["Proposal", "Client", "Status", "Value", "Margin", "Valid until"],
    rows: [
      { Proposal: "Platform transformation", Client: "Vela Systems", Status: "Internal review", Value: "$28,000", Margin: "59%", "Valid until": "Aug 21" },
      { Proposal: "Commerce optimization", Client: "Nova Commerce", Status: "Draft", Value: "$18,000", Margin: "56%", "Valid until": "Aug 28" },
      { Proposal: "Digital strategy sprint", Client: "Common Ground", Status: "Sent", Value: "$12,500", Margin: "64%", "Valid until": "Aug 16" },
      { Proposal: "Brand and web system", Client: "Forma Living", Status: "Viewed", Value: "$22,000", Margin: "55%", "Valid until": "Aug 12" },
    ],
    insight: "The Vela scope can hold a 59% margin if research stays at 32 hours or less.",
  },
  contracts: {
    title: "Contracts",
    eyebrow: "Commercial control",
    description: "Track signatures, obligations, renewal dates, and change control beside the work they govern.",
    action: "New contract",
    metrics: [
      { label: "Active value", value: "$183k", detail: "8 agreements" },
      { label: "Awaiting signature", value: "$42k", detail: "2 contracts", tone: "warning" },
      { label: "Renewing in 60d", value: "$25.5k", detail: "3 retainers" },
      { label: "Signed on time", value: "96%", detail: "+5% this quarter", tone: "positive" },
    ],
    workflow: ["Draft", "Legal review", "Sent", "Negotiation", "Signed", "Renew / close"],
    columns: ["Agreement", "Client", "Status", "Value", "Starts", "Renewal"],
    rows: [
      { Agreement: "Master services agreement", Client: "Northstar Labs", Status: "Active", Value: "$68,400", Starts: "Jan 01", Renewal: "Jan 01, 2027" },
      { Agreement: "Portal delivery SOW", Client: "Halcyon Health", Status: "Active", Value: "$36,000", Starts: "Apr 18", Renewal: "Sep 30" },
      { Agreement: "Brand system SOW", Client: "Fieldnote Studio", Status: "Active", Value: "$24,500", Starts: "Jun 03", Renewal: "Oct 15" },
      { Agreement: "Platform transformation", Client: "Vela Systems", Status: "Awaiting signature", Value: "$28,000", Starts: "Aug 17", Renewal: "—" },
    ],
    insight: "Northstar's renewal window opens in 27 days; prepare the impact review before proposing the next term.",
  },
  clients: {
    title: "Client success",
    eyebrow: "Relationship health",
    description: "See every relationship, commitment, commercial, project, and signal in one client record.",
    action: "Add client",
    metrics: [
      { label: "Active clients", value: "12", detail: "+2 this quarter", tone: "positive" },
      { label: "Portfolio value", value: "$384k", detail: "Trailing 12 months" },
      { label: "Avg. health", value: "87", detail: "+3 points", tone: "positive" },
      { label: "At risk", value: "2", detail: "$46k revenue", tone: "warning" },
    ],
    workflow: ["Won", "Onboarding", "Active", "Expansion", "Renewal", "Alumni"],
    columns: ["Client", "Health", "Active work", "LTV", "Owner", "Next moment"],
    rows: [
      { Client: "Northstar Labs", Health: "94 · Excellent", "Active work": "2 projects", LTV: "$68,400", Owner: "Avery Kim", "Next moment": "QBR · Aug 19" },
      { Client: "Halcyon Health", Health: "81 · Good", "Active work": "1 project", LTV: "$42,750", Owner: "Mina Park", "Next moment": "Review · Aug 12" },
      { Client: "Fieldnote Studio", Health: "72 · Watch", "Active work": "1 project", LTV: "$28,900", Owner: "Sam Rivera", "Next moment": "Direction review · Fri" },
      { Client: "Atlas Finance", Health: "89 · Strong", "Active work": "Retainer", LTV: "$91,200", Owner: "Avery Kim", "Next moment": "Renewal · Sep 01" },
    ],
    insight: "Fieldnote health is slipping because two decisions are overdue. Send one consolidated approval request.",
  },
  onboarding: {
    title: "Client onboarding",
    eyebrow: "First value",
    description: "Standardize every handoff from sales to delivery without making the experience feel generic.",
    action: "Start onboarding",
    metrics: [
      { label: "In onboarding", value: "3", detail: "$62k booked" },
      { label: "Avg. completion", value: "4.2 days", detail: "1.1 days faster", tone: "positive" },
      { label: "Waiting on client", value: "5", detail: "Across 3 accounts", tone: "warning" },
      { label: "First-week CSAT", value: "9.4", detail: "+0.6 this quarter", tone: "positive" },
    ],
    workflow: ["Internal handoff", "Welcome", "Access & assets", "Kickoff", "Plan approved", "First value"],
    columns: ["Client", "Progress", "Owner", "Blocked by", "Kickoff", "Status"],
    rows: [
      { Client: "Fieldnote Studio", Progress: "48%", Owner: "Sam Rivera", "Blocked by": "Brand assets", Kickoff: "Aug 08", Status: "Waiting" },
      { Client: "Lumen Works", Progress: "76%", Owner: "Mina Park", "Blocked by": "Analytics access", Kickoff: "Aug 07", Status: "In progress" },
      { Client: "Common Ground", Progress: "24%", Owner: "Avery Kim", "Blocked by": "None", Kickoff: "Aug 12", Status: "On track" },
    ],
    insight: "Fieldnote can be unblocked with one asset request covering logo files, fonts, and photography rights.",
  },
  projects: {
    title: "Project portfolio",
    eyebrow: "Delivery control",
    description: "Plan scope, milestones, budget, decisions, and delivery health without losing the client context.",
    action: "New project",
    metrics: [
      { label: "In flight", value: "7", detail: "$142k total budget" },
      { label: "On-track", value: "86%", detail: "+4% this month", tone: "positive" },
      { label: "Budget used", value: "63%", detail: "Across active work" },
      { label: "At risk", value: "1", detail: "Halcyon portal", tone: "warning" },
    ],
    workflow: ["Planning", "Kickoff", "In progress", "Client review", "Handoff", "Complete"],
    columns: ["Project", "Client", "Status", "Progress", "Budget", "Due"],
    rows: [
      { Project: "Platform relaunch", Client: "Northstar Labs", Status: "In progress", Progress: "68%", Budget: "$29.2k / $48k", Due: "Sep 18" },
      { Project: "Patient portal", Client: "Halcyon Health", Status: "Client review", Progress: "86%", Budget: "$31.8k / $36k", Due: "Aug 22" },
      { Project: "Brand system", Client: "Fieldnote Studio", Status: "In progress", Progress: "42%", Budget: "$9.4k / $24.5k", Due: "Oct 04" },
      { Project: "Growth experiments", Client: "Atlas Finance", Status: "Retainer", Progress: "61%", Budget: "$5.1k / $8.5k", Due: "Monthly" },
    ],
    insight: "Halcyon needs a scope decision today. The current queue would push the margin below 50%.",
  },
  tasks: {
    title: "Work management",
    eyebrow: "Team execution",
    description: "Turn scope into owned, prioritized work with dependencies, estimates, time, and proof of done.",
    action: "Add task",
    metrics: [
      { label: "Due today", value: "11", detail: "3 high priority", tone: "warning" },
      { label: "Completed this week", value: "38", detail: "+14% vs average", tone: "positive" },
      { label: "Overdue", value: "4", detail: "2 client blockers", tone: "warning" },
      { label: "Focus load", value: "82%", detail: "Healthy allocation" },
    ],
    workflow: ["Backlog", "Ready", "In progress", "Internal review", "Client review", "Done"],
    columns: ["Task", "Project", "Priority", "Status", "Assignee", "Due"],
    rows: [
      { Task: "Approve responsive prototype", Project: "NST-024", Priority: "High", Status: "Today", Assignee: "Avery Kim", Due: "Today" },
      { Task: "QA accessibility fixes", Project: "HAL-011", Priority: "High", Status: "In progress", Assignee: "Mina Park", Due: "Tomorrow" },
      { Task: "Present visual directions", Project: "FLD-008", Priority: "Medium", Status: "Today", Assignee: "Sam Rivera", Due: "Today" },
      { Task: "Document CMS handoff", Project: "NST-024", Priority: "Low", Status: "Backlog", Assignee: "Unassigned", Due: "Aug 14" },
    ],
    insight: "Move the CMS handoff to Jordan; they have 6 hours of available capacity and worked on the last handoff.",
  },
  calendar: {
    title: "Agency calendar",
    eyebrow: "Meetings + delivery rhythm",
    description: "Manage internal events and first-party bookings synchronized with leads, next actions, and the client portal.",
    action: "Add event",
    metrics: [
      { label: "Booking source", value: "M&W", detail: "Owned inside the CRM", tone: "positive" },
      { label: "CRM matching", value: "Automatic", detail: "Lead-linked at booking", tone: "positive" },
      { label: "Changes", value: "Live", detail: "Bookings, cancellations, reschedules" },
      { label: "Follow-up", value: "Connected", detail: "Lead stage and next action", tone: "positive" },
    ],
    workflow: ["Offer times", "Book", "Link lead", "Prepare", "Meet", "Follow through"],
    columns: ["Event", "Type", "Context", "Owner", "Date", "Preparation"],
    rows: [
      { Event: "Halcyon release review", Type: "Client", Context: "HAL-011", Owner: "Mina", Date: "Thu · 10:30", Preparation: "Ready" },
      { Event: "Fieldnote direction review", Type: "Milestone", Context: "FLD-008", Owner: "Sam", Date: "Fri · 14:00", Preparation: "1 item open" },
      { Event: "Northstar QBR", Type: "Success", Context: "Northstar", Owner: "Avery", Date: "Aug 19", Preparation: "Draft brief" },
      { Event: "Invoice run", Type: "Finance", Context: "Monthly", Owner: "Mina", Date: "Aug 28", Preparation: "Scheduled" },
    ],
    insight: "M&W Command is the source of truth for availability, public bookings, reschedules, cancellations, and manual events.",
  },
  scheduling: {
    title: "Scheduling & availability",
    eyebrow: "Native scheduling",
    description: "Create meeting types, define bookable hours, and control the complete self-service booking experience.",
    action: "New meeting type",
    metrics: [],
    workflow: ["Configure", "Publish", "Book", "Confirm", "Reschedule", "Follow up"],
    columns: [],
    rows: [],
    insight: "Availability, booking rules, and appointments are all controlled by the CRM.",
  },
  time: {
    title: "Time & utilization",
    eyebrow: "Delivery economics",
    description: "Connect effort to scope, capacity, profitability, and invoices without turning time into surveillance.",
    action: "Log time",
    metrics: [
      { label: "Logged this week", value: "214h", detail: "78% billable" },
      { label: "Utilization", value: "76%", detail: "Target 74%", tone: "positive" },
      { label: "Unsubmitted", value: "18h", detail: "5 people", tone: "warning" },
      { label: "Billable value", value: "$31.8k", detail: "Current week" },
    ],
    workflow: ["Plan capacity", "Track work", "Review time", "Approve", "Invoice", "Learn"],
    columns: ["Team member", "Logged", "Billable", "Utilization", "Capacity", "Status"],
    rows: [
      { "Team member": "Avery Kim", Logged: "31h", Billable: "25h", Utilization: "81%", Capacity: "7h left", Status: "Submitted" },
      { "Team member": "Mina Park", Logged: "34h", Billable: "29h", Utilization: "85%", Capacity: "4h left", Status: "Submitted" },
      { "Team member": "Sam Rivera", Logged: "28h", Billable: "20h", Utilization: "71%", Capacity: "10h left", Status: "Draft" },
      { "Team member": "Jordan Lee", Logged: "26h", Billable: "18h", Utilization: "69%", Capacity: "12h left", Status: "Draft" },
    ],
    insight: "The team is healthy overall. Jordan can absorb one medium task without crossing the 80% focus threshold.",
  },
  finance: {
    title: "Finance & billing",
    eyebrow: "Cash and margin",
    description: "Connect project economics, retainers, expenses, invoices, payments, and forecasts.",
    action: "Create invoice",
    metrics: [
      { label: "Collected MTD", value: "$71.4k", detail: "82% of target", tone: "positive" },
      { label: "Receivables", value: "$19.4k", detail: "2 invoices due", tone: "warning" },
      { label: "Gross margin", value: "57.8%", detail: "+2.8% vs target", tone: "positive" },
      { label: "Recurring revenue", value: "$25.5k", detail: "3 retainers" },
    ],
    workflow: ["Commercial plan", "Track cost", "Draft invoice", "Approve", "Collect", "Reconcile"],
    columns: ["Invoice", "Client", "Status", "Amount", "Issued", "Due / paid"],
    rows: [
      { Invoice: "INV-2026-041", Client: "Northstar Labs", Status: "Paid", Amount: "$12,000", Issued: "Jul 01", "Due / paid": "Paid Jul 12" },
      { Invoice: "INV-2026-046", Client: "Halcyon Health", Status: "Sent", Amount: "$14,500", Issued: "Jul 28", "Due / paid": "Due Aug 11" },
      { Invoice: "INV-2026-049", Client: "Fieldnote Studio", Status: "Draft", Amount: "$8,200", Issued: "—", "Due / paid": "Not sent" },
      { Invoice: "RET-2026-08", Client: "Atlas Finance", Status: "Scheduled", Amount: "$8,500", Issued: "Aug 28", "Due / paid": "Sep 07" },
    ],
    insight: "Halcyon's invoice is likely to pay on time. Prepare the Fieldnote draft after Friday's milestone approval.",
  },
  team: {
    title: "People & capacity",
    eyebrow: "Healthy delivery",
    description: "Manage roles, teams, skills, workload, cost, access, performance rhythms, and leave.",
    action: "Invite member",
    metrics: [
      { label: "Team", value: "8", detail: "6 employees · 2 partners" },
      { label: "Capacity used", value: "76%", detail: "Healthy range", tone: "positive" },
      { label: "Available next week", value: "52h", detail: "Across 4 people" },
      { label: "Overallocated", value: "1", detail: "Mina · 6h", tone: "warning" },
    ],
    workflow: ["Invite", "Onboard", "Set role", "Plan capacity", "Coach", "Grow"],
    columns: ["Person", "Role", "Team", "Allocation", "Availability", "Access"],
    rows: [
      { Person: "Avery Kim", Role: "Agency lead", Team: "Leadership", Allocation: "81%", Availability: "7h", Access: "Owner" },
      { Person: "Mina Park", Role: "Delivery director", Team: "Delivery", Allocation: "106%", Availability: "-6h", Access: "Admin" },
      { Person: "Sam Rivera", Role: "Design lead", Team: "Creative", Allocation: "72%", Availability: "10h", Access: "Member" },
      { Person: "Jordan Lee", Role: "Product designer", Team: "Creative", Allocation: "69%", Availability: "12h", Access: "Member" },
    ],
    insight: "Shift Halcyon QA ownership from Mina to Jordan to rebalance 5.5 hours without changing the deadline.",
  },
  documents: {
    title: "Documents & knowledge",
    eyebrow: "Agency memory",
    description: "Keep briefs, contracts, assets, decisions, playbooks, and version history attached to the work.",
    action: "Add document",
    metrics: [
      { label: "Documents", value: "1,284", detail: "Across 12 clients" },
      { label: "Needs review", value: "9", detail: "3 policies", tone: "warning" },
      { label: "Client shared", value: "184", detail: "Role-scoped links" },
      { label: "Knowledge coverage", value: "86%", detail: "+11% this quarter", tone: "positive" },
    ],
    workflow: ["Capture", "Classify", "Review", "Approve", "Share", "Archive"],
    columns: ["Document", "Type", "Context", "Owner", "Version", "Updated"],
    rows: [
      { Document: "Platform relaunch brief", Type: "Brief", Context: "NST-024", Owner: "Avery", Version: "v4", Updated: "12 min ago" },
      { Document: "Patient portal SOW", Type: "Contract", Context: "HAL-011", Owner: "Mina", Version: "Signed", Updated: "Jul 18" },
      { Document: "Creative review playbook", Type: "Playbook", Context: "Agency", Owner: "Sam", Version: "v7", Updated: "Aug 02" },
      { Document: "Brand asset inventory", Type: "Assets", Context: "FLD-008", Owner: "Jordan", Version: "v2", Updated: "Yesterday" },
    ],
    insight: "The pricing playbook conflicts with two recent proposals. Review the day-rate section before the next send.",
  },
  blog: {
    title: "Blog publishing",
    eyebrow: "Content engine",
    description: "Create, optimize, schedule, publish, and maintain search-ready articles from one editorial workspace.",
    action: "New blog post",
    metrics: [
      { label: "Public route", value: "/blog", detail: "Index and article pages", tone: "positive" },
      { label: "Publishing states", value: "3", detail: "Draft · Published · Archived" },
      { label: "SEO metadata", value: "Included", detail: "Title, description, canonical and OG", tone: "positive" },
      { label: "Discovery", value: "Automatic", detail: "Published posts enter the sitemap" },
    ],
    workflow: ["Draft", "Edit", "SEO review", "Publish", "Distribute", "Refresh"],
    columns: ["Post", "Status", "Category", "Slug", "Featured", "Published"],
    rows: [],
    insight: "Write for a specific search intent, publish only complete work, and refresh posts when the underlying advice changes.",
  },
  work: {
    title: "Work & proof",
    eyebrow: "Case study publishing",
    description: "Turn delivered projects into credible case studies with context, approach, verifiable results, and SEO metadata.",
    action: "New work post",
    metrics: [
      { label: "Public route", value: "/work", detail: "Portfolio and case study pages", tone: "positive" },
      { label: "Proof structure", value: "Complete", detail: "Challenge · Solution · Results" },
      { label: "Featured work", value: "Supported", detail: "Control priority on the public listing" },
      { label: "Discovery", value: "Automatic", detail: "Published work enters the sitemap" },
    ],
    workflow: ["Draft", "Verify proof", "Client review", "Publish", "Promote", "Refresh"],
    columns: ["Case study", "Status", "Client", "Industry", "Featured", "Published"],
    rows: [],
    insight: "The strongest case studies connect a clear business constraint to a specific intervention and a result you can substantiate.",
  },
  "seo-pages": {
    title: "SEO landing pages",
    eyebrow: "Organic acquisition",
    description: "Create focused service and location pages with controlled URLs, indexation, canonical tags, and social metadata.",
    action: "New SEO page",
    metrics: [
      { label: "URL control", value: "Built in", detail: "Reserved routes are protected", tone: "positive" },
      { label: "Indexation", value: "Per page", detail: "Use no-index while testing" },
      { label: "Canonical tags", value: "Supported", detail: "Prevent competing URL signals" },
      { label: "Sitemap", value: "Automatic", detail: "Only eligible published pages appear" },
    ],
    workflow: ["Research", "Draft", "SEO review", "Publish", "Measure", "Improve"],
    columns: ["Page", "Status", "URL", "Primary keyword", "No index", "Updated"],
    rows: [],
    insight: "Give each landing page a distinct search intent and genuinely useful content; near-duplicate pages weaken the whole site.",
  },
  automations: {
    title: "Automations",
    eyebrow: "System leverage",
    description: "Connect triggers, conditions, approvals, and actions across your agency workflow.",
    action: "New automation",
    metrics: [
      { label: "Active automations", value: "18", detail: "Across 7 workflows" },
      { label: "Runs this month", value: "1,284", detail: "+22%", tone: "positive" },
      { label: "Time returned", value: "46h", detail: "Est. this month", tone: "positive" },
      { label: "Needs attention", value: "2", detail: "Permission changes", tone: "warning" },
    ],
    workflow: ["Trigger", "Filter", "Enrich", "Propose", "Approve", "Act & log"],
    columns: ["Automation", "Trigger", "Action", "Runs", "Last run", "Status"],
    rows: [
      { Automation: "Lead response SLA", Trigger: "New lead", Action: "Draft reply + notify", Runs: "48", "Last run": "18 min ago", Status: "Active" },
      { Automation: "Invoice chase", Trigger: "3 days overdue", Action: "Prepare reminder", Runs: "11", "Last run": "Yesterday", Status: "Active" },
      { Automation: "Project risk scan", Trigger: "Weekdays · 09:00", Action: "Flag risk", Runs: "126", "Last run": "Today", Status: "Active" },
      { Automation: "Client QBR prep", Trigger: "21 days before QBR", Action: "Build impact brief", Runs: "8", "Last run": "Aug 01", Status: "Review" },
    ],
    insight: "Add approval to the lead-response workflow before enabling automatic external sends.",
  },
  reports: {
    title: "Reports & forecasting",
    eyebrow: "Decision intelligence",
    description: "Understand revenue, pipeline, utilization, delivery, client health, and cash from one model.",
    action: "Build report",
    metrics: [
      { label: "Forecast revenue", value: "$92.8k", detail: "Next 60 days" },
      { label: "Forecast confidence", value: "84%", detail: "+6 points", tone: "positive" },
      { label: "Utilization", value: "76%", detail: "2% above plan" },
      { label: "Revenue concentration", value: "29%", detail: "Top client", tone: "warning" },
    ],
    workflow: ["Question", "Define metric", "Validate data", "Analyze", "Share", "Decide"],
    columns: ["Report", "Owner", "Cadence", "Coverage", "Last run", "Status"],
    rows: [
      { Report: "Weekly operating review", Owner: "Avery", Cadence: "Weekly", Coverage: "Full agency", "Last run": "Today", Status: "Ready" },
      { Report: "Pipeline forecast", Owner: "Mina", Cadence: "Live", Coverage: "Revenue", "Last run": "Now", Status: "Ready" },
      { Report: "Project margin review", Owner: "Avery", Cadence: "Weekly", Coverage: "Delivery", "Last run": "Mon", Status: "2 flags" },
      { Report: "Client portfolio health", Owner: "Sam", Cadence: "Monthly", Coverage: "Success", "Last run": "Aug 01", Status: "Ready" },
    ],
    insight: "Revenue is healthy, but 29% concentration in Northstar is above the 25% internal guardrail.",
  },
  settings: {
    title: "Workspace settings",
    eyebrow: "Control center",
    description: "Configure identity, roles, security, commercial rules, integrations, AI policy, and audit retention.",
    action: "Save changes",
    metrics: [
      { label: "Security posture", value: "Strong", detail: "2 recommendations", tone: "positive" },
      { label: "Active integrations", value: "7", detail: "All healthy" },
      { label: "Roles", value: "4", detail: "Owner, admin, lead, member" },
      { label: "Audit retention", value: "365d", detail: "Organization policy" },
    ],
    workflow: ["Configure", "Validate", "Review access", "Approve", "Apply", "Audit"],
    columns: ["Area", "Configuration", "Owner", "Last changed", "Status", "Action"],
    rows: [
      { Area: "Authentication", Configuration: "Email + Google", Owner: "Avery", "Last changed": "Jul 14", Status: "Strong", Action: "Review" },
      { Area: "AI action policy", Configuration: "Approval required", Owner: "Avery", "Last changed": "Aug 02", Status: "Safe", Action: "Configure" },
      { Area: "Finance", Configuration: "USD · Net 14", Owner: "Mina", "Last changed": "Jun 18", Status: "Active", Action: "Edit" },
      { Area: "Data retention", Configuration: "365 days", Owner: "Avery", "Last changed": "May 30", Status: "Active", Action: "Review" },
    ],
    insight: "Enable a second factor before granting another owner role. Current sessions and access remain healthy.",
  },
};

export const agencyModules = Object.keys(moduleConfigs);
