import Link from "next/link";
import { AlertTriangle, ArrowUpRight, BriefcaseBusiness, CircleDollarSign, HeartPulse, TimerReset, TrendingUp, WalletCards } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { getReportsData } from "@/lib/dal";

type ReportsData = Awaited<ReturnType<typeof getReportsData>>;

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export function ReportsWorkspace({ data }: { data: ReportsData }) {
  const maxMonth = Math.max(1, ...data.months.flatMap((month) => [month.revenue, month.expenses]));
  return (
    <div className="admin-page">
      <div className="admin-page-header"><div className="max-w-3xl"><p className="text-[10px] font-semibold uppercase tracking-[0.17em] text-muted-foreground">Live decision intelligence</p><h1 className="admin-page-title">Reports &amp; forecasting</h1><p className="admin-page-description">Financial, commercial, delivery, and relationship indicators calculated directly from your workspace records.</p></div><div className="admin-actions"><Button nativeButton={false} render={<Link href="/app/ai" />} className="h-9">Analyze with M&amp;W AI <ArrowUpRight className="size-4" /></Button></div></div>

      <div className="admin-metrics mt-7">
        {[{ label: "60-day forecast", value: money.format(data.metrics.forecast60Days), detail: `${data.metrics.forecastConfidence.toFixed(0)}% average lead confidence`, icon: TrendingUp }, { label: "Utilization", value: `${data.metrics.utilization.toFixed(1)}%`, detail: "Billable share of logged time", icon: TimerReset }, { label: "Gross margin", value: `${data.metrics.grossMargin.toFixed(1)}%`, detail: `${money.format(data.metrics.paidRevenue)} collected`, icon: CircleDollarSign }, { label: "Revenue concentration", value: `${data.metrics.revenueConcentration.toFixed(1)}%`, detail: data.topClient ? `Largest client: ${data.topClient.company}` : "No paid invoices yet", icon: WalletCards }].map((metric) => <div key={metric.label} className="admin-metric-card"><div className="flex items-start justify-between"><div><p className="text-xs text-muted-foreground">{metric.label}</p><p className="mt-3 text-2xl font-semibold tracking-[-0.04em]">{metric.value}</p></div><span className="grid size-8 place-items-center rounded-lg bg-blue-50 text-blue-700"><metric.icon className="size-4" /></span></div><p className="mt-3 text-[11px] text-muted-foreground">{metric.detail}</p></div>)}
      </div>

      <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_0.75fr]">
        <section className="admin-card rounded-2xl p-4 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Cash performance</h2><p className="mt-1 text-[11px] text-muted-foreground">Paid invoices against recorded expenses · last six months</p></div><Badge variant="outline" className="bg-emerald-50 text-emerald-700">Live</Badge></div><div className="mt-8 flex h-52 items-end gap-2 sm:h-60 sm:gap-6">{data.months.map((month) => <div key={month.key} className="flex h-full min-w-0 flex-1 flex-col justify-end"><div className="flex flex-1 items-end justify-center gap-1"><div className="w-2/5 rounded-t-md bg-blue-600" style={{ height: `${Math.max(month.revenue ? 5 : 1, month.revenue / maxMonth * 100)}%` }} title={`Revenue ${money.format(month.revenue)}`} /><div className="w-2/5 rounded-t-md bg-orange-300" style={{ height: `${Math.max(month.expenses ? 5 : 1, month.expenses / maxMonth * 100)}%` }} title={`Expenses ${money.format(month.expenses)}`} /></div><p className="mt-3 text-center text-[9px] text-muted-foreground sm:text-[10px]">{month.label}</p></div>)}</div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 border-t pt-4 text-[10px] text-muted-foreground"><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-blue-600" />Collected revenue</span><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-orange-300" />Expenses</span><span className="font-semibold text-foreground sm:ml-auto">Recurring {money.format(data.metrics.recurringRevenue)}/mo</span></div></section>

        <section className="rounded-2xl border bg-white p-5 shadow-sm sm:p-6"><h2 className="text-sm font-semibold">Operating health</h2><p className="mt-1 text-[11px] text-muted-foreground">Signals that need a weekly decision</p><div className="mt-5 space-y-3">{[{ label: "Active clients", value: data.health.activeClients, detail: `${data.health.averageClientHealth.toFixed(0)} average health`, icon: BriefcaseBusiness, href: "/app/clients" }, { label: "At-risk projects", value: data.health.projectRisks, detail: "Burn, progress, or deadline variance", icon: AlertTriangle, href: "/app/projects" }, { label: "Overdue invoices", value: data.health.overdueInvoices, detail: "Marked overdue or past due", icon: CircleDollarSign, href: "/app/finance" }, { label: "Relationship health", value: `${data.health.averageClientHealth.toFixed(0)}/100`, detail: "Across every client", icon: HeartPulse, href: "/app/clients" }].map((item) => <Link key={item.label} href={item.href} className="flex items-center gap-3 rounded-xl border bg-muted/15 p-3.5 transition hover:bg-muted/40"><span className="grid size-8 place-items-center rounded-lg bg-white shadow-sm"><item.icon className="size-3.5" /></span><div className="flex-1"><p className="text-xs font-semibold">{item.label}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.detail}</p></div><span className="text-lg font-semibold">{item.value}</span></Link>)}</div></section>
      </div>

      <div className="mt-5 grid gap-5 xl:grid-cols-[0.8fr_1.2fr]">
        <section className="admin-card rounded-2xl p-4 sm:p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Pipeline coverage</h2><Button nativeButton={false} render={<Link href="/app/leads" />} variant="ghost" size="sm">Open leads <ArrowUpRight className="size-3.5" /></Button></div><div className="mt-4 space-y-2">{data.pipeline.map((stage) => <div key={stage.stage} className="grid gap-2 rounded-xl bg-muted/25 px-3 py-3 min-[480px]:grid-cols-[90px_1fr_auto] min-[480px]:items-center"><span className="text-[11px] font-semibold">{stage.stage}</span><div className="h-1.5 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.min(100, stage.count * 18)}%` }} /></div><span className="text-[10px] text-muted-foreground">{stage.count} · {money.format(stage.value)}</span></div>)}</div></section>
        <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Project risk register</h2><p className="mt-1 text-[11px] text-muted-foreground">Flagged when budget burn leads progress by 15 points or the due date has passed. The 50 highest-risk projects are shown.</p></div><Badge variant="outline">{data.health.projectRisks} flags</Badge></div><div className="mt-4 divide-y">{data.projectRisks.map((project) => <div key={project.id} className="grid gap-2 py-3 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="text-xs font-semibold">{project.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{project.client}</p></div><span className="text-[11px]">{project.progress}% progress</span><span className="text-[11px] font-semibold text-orange-700">{project.burn.toFixed(0)}% burn</span></div>)}{!data.projectRisks.length && <div className="py-10 text-center"><HeartPulse className="mx-auto size-5 text-emerald-600" /><p className="mt-2 text-xs text-muted-foreground">No projects currently breach the risk rule.</p></div>}</div></section>
      </div>
    </div>
  );
}
