# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "channels", to: "channels/index.js"
pin_all_from "app/javascript/channels", under: "channels"
pin "notifications"
pin "project_filters"
pin "testimonials"
pin "flowbite", to: "https://cdn.jsdelivr.net/npm/flowbite@4.0.1/dist/flowbite.turbo.min.js"
pin "@fortawesome/fontawesome-free", to: "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.7.2/js/all.min.js"
pin "@rails/actioncable", to: "actioncable.esm.js"
pin "trix", to: "https://cdn.jsdelivr.net/npm/trix@2.1.13/dist/trix.esm.min.js"
pin "@rails/actiontext", to: "actiontext.esm.js"
pin "admin_editor", to: "admin_editor.js"
