ALTER TABLE `Lead` ADD INDEX `Lead_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `Client` ADD INDEX `Client_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `Proposal` ADD INDEX `Proposal_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `Contract` ADD INDEX `Contract_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `Project` ADD INDEX `Project_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `Task` ADD INDEX `Task_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `Invoice` ADD INDEX `Invoice_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `InvoiceItem` ADD INDEX `InvoiceItem_invoiceId_idx`(`invoiceId`);
ALTER TABLE `Expense` ADD INDEX `Expense_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `Retainer` ADD INDEX `Retainer_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `Document` ADD INDEX `Document_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `Activity` ADD INDEX `Activity_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `CalendarEvent` ADD INDEX `CalendarEvent_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `Automation` ADD INDEX `Automation_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `KnowledgeItem` ADD INDEX `KnowledgeItem_organizationId_id_idx`(`organizationId`, `id`);
ALTER TABLE `BackgroundJob` ADD INDEX `BackgroundJob_status_priority_runAt_createdAt_idx`(`status`, `priority`, `runAt`, `createdAt`);
ALTER TABLE `BackgroundJob` ADD INDEX `BackgroundJob_status_completedAt_idx`(`status`, `completedAt`);
ALTER TABLE `BlogPost` ADD INDEX `BlogPost_organizationId_updatedAt_id_idx`(`organizationId`, `updatedAt`, `id`);
ALTER TABLE `WorkPost` ADD INDEX `WorkPost_organizationId_updatedAt_id_idx`(`organizationId`, `updatedAt`, `id`);
ALTER TABLE `SeoPage` ADD INDEX `SeoPage_organizationId_updatedAt_id_idx`(`organizationId`, `updatedAt`, `id`);
